In [1]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup, Comment
import json
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
totalData = []
url = "https://baseballsavant.mlb.com/player/full_spray?playerId=545361"
json_url = urlopen(url)
data = json.loads(json_url.read())
df = pd.DataFrame(data)
df

,des,events,game_date,hc_x,hc_x_ft,hc_y,hc_y_ft,outs,pre_ball_count,pre_strike_count,sport_id,year
0,Mike Trout singles on a line drive to center f...,single,2019-05-13,122.39,-8.4113,70.51,312.1967,2,1,0,1,2019
1,Mike Trout singles on a ground ball to left fi...,single,2019-05-13,98.91,-63.1197,96.12,252.5254,1,0,1,1,2019
2,Mike Trout singles on a line drive to right fi...,single,2019-05-13,189.86,148.7938,126.77,181.1109,0,2,2,1,2019
3,"Mike Trout grounds out, second baseman Ehire A...",field_out,2019-05-13,115.26,-25.0242,147.60,132.5770,1,3,1,1,2019
4,Mike Trout homers (24) on a fly ball to left f...,home_run,2019-07-03,1.00,-291.2500,84.74,279.0408,0,2,2,1,2019
5,Mike Trout homers (23) on a fly ball to right ...,home_run,2019-07-03,179.33,124.2589,28.89,409.1713,1,1,0,1,2019
6,Mike Trout pops out to first baseman Ronald Gu...,field_out,2019-07-02,172.60,108.5780,171.83,76.1211,2,1,2,1,2019
7,Mike Trout flies out sharply to center fielder...,field_out,2019-07-02,124.86,-2.6562,42.55,377.3435,0,1,2,1,2019
8,"Mike Trout grounds out, shortstop Elvis Andrus...",field_out,2019-07-02,102.95,-53.7065,151.24,124.0958,2,3,1,1,2019
9,"Mike Trout grounds out, second baseman Danny S...",field_out,2019-04-17,122.94,-7.1298,145.18,138.2156,1,1,1,1,2019
10,Mike Trout singles on a line drive to right fi...,single,2019-04-17,162.98,86.1634,78.94,292.5548,0,1,1,1,2019
11,"Mike Trout grounds out sharply, second baseman...",field_out,2019-04-17,148.38,52.1454,147.00,133.9750,1,1,0,1,2019
12,Mike Trout singles on a line drive to left fie...,single,2019-06-22,83.86,-98.1862,126.17,182.5089,1,2,1,1,2019
13,"Mike Trout grounds into a double play, shortst...",grounded_into_double_play,2019-05-14,105.21,-48.4407,155.54,114.0768,0,1,2,1,2019
14,"Mike Trout grounds out sharply, third baseman ...",field_out,2019-05-14,95.68,-70.6456,165.87,90.0079,1,2,2,1,2019
15,"Mike Trout grounds out sharply, third baseman ...",field_out,2019-06-02,104.19,-50.8173,171.97,75.7949,2,2,1,1,2019
16,Mike Trout singles on a line drive to left fie...,single,2019-06-02,96.46,-68.8282,131.08,171.0686,2,0,1,1,2019
17,Mike Trout singles on a ground ball to left fi...,single,2019-06-02,74.79,-119.3193,115.19,208.0923,0,1,0,1,2019
18,Mike Trout singles on a line drive to right fi...,single,2019-06-02,156.49,71.0417,108.70,223.2140,1,1,1,1,2019
19,"Mike Trout grounds out, third baseman Matt Car...",field_out,2019-06-21,107.45,-43.2215,173.56,72.0902,0,0,0,1,2019
20,Mike Trout singles on a soft ground ball to th...,single,2019-06-21,107.45,-43.2215,178.64,60.2538,1,3,2,1,2019
21,Mike Trout singles on a line drive to center f...,single,2019-06-21,116.49,-22.1583,67.66,318.8372,1,2,2,1,2019
22,"Mike Trout grounds out, catcher Omar Narvaez t...",field_out,2019-04-02,125.49,-1.1883,202.90,3.7280,2,1,2,1,2019
23,Mike Trout flies out to right fielder Mitch Ha...,field_out,2019-04-02,170.61,103.9413,126.85,180.9245,2,0,0,1,2019
24,Mike Trout singles on a line drive to left fie...,single,2019-04-02,78.04,-111.7468,107.08,226.9886,1,1,1,1,2019
25,"Mike Trout grounds out, shortstop Elvis Andrus...",field_out,2019-04-15,116.55,-22.0185,136.91,157.4847,2,0,0,1,2019
26,Mike Trout homers (19) on a fly ball to left f...,home_run,2019-06-16,17.03,-253.9001,60.72,335.0074,1,3,2,1,2019
27,Mike Trout flies out to center fielder Joey Ga...,field_out,2019-07-04,128.86,6.6638,86.26,275.4992,1,3,2,1,2019
28,Mike Trout lines out to right fielder Shin-Soo...,field_out,2019-07-04,170.82,104.4306,76.53,298.1701,0,3,1,1,2019
29,Mike Trout singles on a line drive to right fi...,single,2019-07-04,177.92,120.9736,131.02,171.2084,2,0,2,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4133,None,field_out,2009-07-27,155.62,69.0146,170.68,78.8006,1,0,0,16,2009
4134,None,field_out,2009-07-27,125.50,-1.1650,89.36,268.2762,2,0,0,16,2009
4135,None,field_out,2009-07-27,114.46,-26.8882,77.31,296.3527,2,0,0,16,2009
4136,None,sac_fly,2009-07-27,115.46,-24.5582,76.31,298.6827,0,0,0,16,2009
4137,None,field_out,2009-07-21,124.50,-3.4950,202.81,3.9377,1,0,0,16,2009
4138,None,field_out,2009-07-21,200.80,174.2840,106.43,228.5031,2,0,0,16,2009
4139,None,field_out,2009-07-21,157.63,73.6979,116.47,205.1099,2,0,0,16,2009
4140,None,force_out,2009-07-21,106.43,-45.5981,178.71,60.0907,2,0,0,16,2009
4141,None,single,2009-08-25,120.48,-12.8616,66.27,322.0759,0,0,0,16,2009
4142,None,field_out,2009-08-25,131.53,12.8849,67.27,319.7459,1,0,0,16,2009
4143,None,field_out,2009-08-25,91.37,-80.6879,86.35,275.2895,2,0,0,16,2009
4144,None,single,2009-08-25,98.39,-64.3313,73.29,305.7193,0,0,0,16,2009
4145,None,field_out,2009-08-07,103.41,-52.6347,182.73,50.7241,0,0,0,16,2009
4146,None,single,2009-08-07,107.43,-43.2681,168.67,83.4839,1,1,0,16,2009
4147,None,triple,2009-08-07,182.73,132.1809,77.31,296.3527,0,0,0,16,2009
4148,None,field_out,2009-08-04,105.42,-47.9514,80.32,289.3394,1,0,0,16,2009
4149,None,field_out,2009-08-04,123.49,-5.8483,209.84,-12.4422,2,0,0,16,2009
4150,None,single,2009-08-04,120.48,-12.8616,116.47,205.1099,2,0,0,16,2009
4151,None,single,2009-08-04,119.48,-15.1916,143.57,141.9669,2,0,0,16,2009
4152,None,double,2009-07-18,122.49,-8.1783,64.26,326.7592,2,0,0,16,2009
4153,None,field_out,2009-07-18,104.42,-50.2814,159.64,104.5238,1,0,0,16,2009
4154,None,single,2009-07-18,105.42,-47.9514,145.58,137.2836,0,0,0,16,2009
4155,None,field_error,2009-07-18,105.42,-47.9514,160.64,102.1938,1,0,0,16,2009
4156,None,grounded_into_double_play,2009-07-15,134.54,19.8982,163.65,95.1805,0,0,0,16,2009
4157,None,field_out,2009-07-15,116.47,-22.2049,171.69,76.4473,1,0,0,16,2009
4158,None,single,2009-07-15,139.56,31.5948,133.53,165.3601,0,0,0,16,2009
4159,None,single,2009-09-06,74.30,-120.4610,138.55,153.6635,1,0,0,14,2009
4160,None,field_out,2009-09-04,198.80,169.6240,110.44,219.1598,0,1,0,14,2009
4161,None,field_out,2009-09-04,103.41,-52.6347,180.72,55.4074,1,0,0,14,2009
4162,None,field_out,2009-09-04,176.71,118.1543,120.48,195.7666,0,0,0,14,2009

In [3]:
df.to_csv('troutSpray.csv')

In [4]:
df_hits = df[(df['events']!='force_out') & (df['events']!='field_out')]

In [5]:
df_hits

,des,events,game_date,hc_x,hc_x_ft,hc_y,hc_y_ft,outs,pre_ball_count,pre_strike_count,sport_id,year
0,Mike Trout singles on a line drive to center f...,single,2019-05-13,122.39,-8.4113,70.51,312.1967,2,1,0,1,2019
1,Mike Trout singles on a ground ball to left fi...,single,2019-05-13,98.91,-63.1197,96.12,252.5254,1,0,1,1,2019
2,Mike Trout singles on a line drive to right fi...,single,2019-05-13,189.86,148.7938,126.77,181.1109,0,2,2,1,2019
4,Mike Trout homers (24) on a fly ball to left f...,home_run,2019-07-03,1.00,-291.2500,84.74,279.0408,0,2,2,1,2019
5,Mike Trout homers (23) on a fly ball to right ...,home_run,2019-07-03,179.33,124.2589,28.89,409.1713,1,1,0,1,2019
10,Mike Trout singles on a line drive to right fi...,single,2019-04-17,162.98,86.1634,78.94,292.5548,0,1,1,1,2019
12,Mike Trout singles on a line drive to left fie...,single,2019-06-22,83.86,-98.1862,126.17,182.5089,1,2,1,1,2019
13,"Mike Trout grounds into a double play, shortst...",grounded_into_double_play,2019-05-14,105.21,-48.4407,155.54,114.0768,0,1,2,1,2019
16,Mike Trout singles on a line drive to left fie...,single,2019-06-02,96.46,-68.8282,131.08,171.0686,2,0,1,1,2019
17,Mike Trout singles on a ground ball to left fi...,single,2019-06-02,74.79,-119.3193,115.19,208.0923,0,1,0,1,2019
18,Mike Trout singles on a line drive to right fi...,single,2019-06-02,156.49,71.0417,108.70,223.2140,1,1,1,1,2019
20,Mike Trout singles on a soft ground ball to th...,single,2019-06-21,107.45,-43.2215,178.64,60.2538,1,3,2,1,2019
21,Mike Trout singles on a line drive to center f...,single,2019-06-21,116.49,-22.1583,67.66,318.8372,1,2,2,1,2019
24,Mike Trout singles on a line drive to left fie...,single,2019-04-02,78.04,-111.7468,107.08,226.9886,1,1,1,1,2019
26,Mike Trout homers (19) on a fly ball to left f...,home_run,2019-06-16,17.03,-253.9001,60.72,335.0074,1,3,2,1,2019
29,Mike Trout singles on a line drive to right fi...,single,2019-07-04,177.92,120.9736,131.02,171.2084,2,0,2,1,2019
30,Mike Trout homers (25) on a fly ball to left c...,home_run,2019-07-04,31.19,-220.9073,34.68,395.6806,1,3,1,1,2019
31,Mike Trout singles on a line drive to center f...,single,2019-06-23,111.76,-33.1792,93.91,257.6747,0,1,0,1,2019
32,Mike Trout singles on a line drive to left fie...,single,2019-06-23,61.73,-149.7491,99.39,244.9063,0,2,0,1,2019
36,"Mike Trout doubles (18) to left field, on fan ...",double,2019-06-20,69.00,-132.8100,126.00,182.9050,0,3,2,1,2019
37,Mike Trout singles on a sharp line drive to ce...,single,2019-06-20,152.09,60.7897,59.88,336.9646,2,1,1,1,2019
40,Mike Trout singles on a sharp line drive to le...,single,2019-06-16,46.07,-186.2369,81.86,285.7512,0,0,0,1,2019
43,Mike Trout doubles (16) on a line drive to cen...,double,2019-06-14,98.50,-64.0750,55.11,348.0787,1,3,1,1,2019
49,Mike Trout reaches on a throwing error by thir...,field_error,2019-04-01,104.19,-50.8173,165.38,91.1496,1,1,2,1,2019
52,Mike Trout homers (14) on a fly ball to left f...,home_run,2019-06-01,1.00,-291.2500,68.22,317.5324,0,2,1,1,2019
53,Mike Trout singles on a line drive to center f...,single,2019-06-01,123.46,-5.9182,95.73,253.4341,0,3,1,1,2019
55,Mike Trout doubles (14) on a sharp line drive ...,double,2019-05-30,32.71,-217.3657,107.59,225.8003,1,3,2,1,2019
56,Mike Trout singles on a fly ball to right fiel...,single,2019-05-30,173.66,111.0478,137.22,156.7624,1,0,0,1,2019
57,Mike Trout homers (26) on a fly ball to left c...,home_run,2019-07-05,50.14,-176.7538,47.24,366.4158,0,3,2,1,2019
60,Mike Trout singles on a sharp line drive to le...,single,2019-06-19,69.75,-131.0625,70.98,311.1016,2,0,1,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4105,None,single,2009-07-07,135.54,22.2282,171.69,76.4473,0,0,0,16,2009
4107,None,double,2009-07-07,163.65,87.7245,109.44,221.4898,1,0,0,16,2009
4108,None,single,2009-09-03,115.46,-24.5582,173.69,71.7873,1,0,0,14,2009
4110,None,single,2009-09-05,157.63,73.6979,126.51,181.7167,1,0,0,14,2009
4112,None,sac_bunt,2009-09-02,112.45,-31.5715,193.78,24.9776,0,0,0,14,2009
4113,None,single,2009-09-02,172.69,108.7877,117.47,202.7799,0,0,1,14,2009
4116,None,sac_bunt,2009-08-29,114.46,-26.8882,185.74,43.7108,0,0,0,16,2009
4118,None,double,2009-08-17,180.72,127.4976,135.54,160.6768,1,0,0,16,2009
4119,None,single,2009-08-17,80.32,-106.4344,150.60,125.5870,1,0,0,16,2009
4124,None,single,2009-08-15,172.69,108.7877,104.42,233.1864,1,0,0,16,2009
4125,None,single,2009-08-09,156.63,71.3679,174.70,69.4340,2,0,0,16,2009
4126,None,field_error,2009-08-09,102.41,-54.9647,167.67,85.8139,1,0,0,16,2009
4127,None,single,2009-08-09,183.73,134.5109,112.45,214.4765,0,0,0,16,2009
4128,None,home_run,2009-08-06,36.14,-209.3738,69.28,315.0626,1,1,1,16,2009
4129,None,single,2009-08-06,108.43,-40.9381,176.71,64.7507,0,0,0,16,2009
4130,None,field_error,2009-08-06,106.43,-45.5981,178.71,60.0907,1,0,0,16,2009
4131,None,triple,2009-08-06,121.49,-10.5083,62.25,331.4425,2,0,0,16,2009
4136,None,sac_fly,2009-07-27,115.46,-24.5582,76.31,298.6827,0,0,0,16,2009
4141,None,single,2009-08-25,120.48,-12.8616,66.27,322.0759,0,0,0,16,2009
4144,None,single,2009-08-25,98.39,-64.3313,73.29,305.7193,0,0,0,16,2009
4146,None,single,2009-08-07,107.43,-43.2681,168.67,83.4839,1,1,0,16,2009
4147,None,triple,2009-08-07,182.73,132.1809,77.31,296.3527,0,0,0,16,2009
4150,None,single,2009-08-04,120.48,-12.8616,116.47,205.1099,2,0,0,16,2009
4151,None,single,2009-08-04,119.48,-15.1916,143.57,141.9669,2,0,0,16,2009
4152,None,double,2009-07-18,122.49,-8.1783,64.26,326.7592,2,0,0,16,2009
4154,None,single,2009-07-18,105.42,-47.9514,145.58,137.2836,0,0,0,16,2009
4155,None,field_error,2009-07-18,105.42,-47.9514,160.64,102.1938,1,0,0,16,2009
4156,None,grounded_into_double_play,2009-07-15,134.54,19.8982,163.65,95.1805,0,0,0,16,2009
4158,None,single,2009-07-15,139.56,31.5948,133.53,165.3601,0,0,0,16,2009
4159,None,single,2009-09-06,74.30,-120.4610,138.55,153.6635,1,0,0,14,2009

In [6]:
df_hits = df[(df['events']=='single') | (df['events']=='double') | (df['events']=='triple') | (df['events']=='home_run')]
df_hits["hc_x"] = pd.to_numeric(df_hits["hc_x"])
df_hits["hc_x_ft"] = pd.to_numeric(df_hits["hc_x_ft"])
df_hits["hc_y"] = pd.to_numeric(df_hits["hc_y"])
df_hits["hc_y_ft"] = pd.to_numeric(df_hits["hc_y_ft"])
df_avg = pd.pivot_table(df_hits,index=['year'], columns = 'events', values = ["hc_y","hc_x","hc_y_ft","hc_x_ft"])

/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [7]:
df_avg

              hc_x                                        hc_x_ft              \
events      double    home_run      single      triple     double    home_run
year
2009    149.167143   36.140000  122.677500  136.977143  53.979443 -209.373800
2010    132.888929   90.561000  119.438333  127.396667  16.051204  -82.572870
2011    100.608621   65.792353  120.943028  104.108462 -59.161914 -140.283818
2012    107.267419   95.964194  121.115072  125.037692 -43.646913  -69.983429
2013    112.500513  109.102222  122.498783  142.793333 -31.453805  -39.371822
2014     91.931538   99.732778  112.777416  126.951111 -79.379515  -61.202628
2015    100.944063  114.649512  126.232366  176.461667 -58.380334  -26.446637
2016    133.486250   99.358621  118.232804  143.246000  17.442963  -62.074414
2017     99.146923   85.939697  118.118387  106.372500 -62.567669  -93.340506
2018     91.730833   82.183333  119.628125  102.222500 -79.847158 -102.092833
2019    100.489444   76.539286  117.764318  190.810000 -59.439594 -115.243464

                                     hc_y                                     \
events     single      triple      double   home_run      single      triple
year
2009    -7.741425   25.576743  100.831429  69.280000  132.383542   73.868571
2010   -15.288683    3.254233  116.251071  66.565000  138.259365   96.608889
2011   -11.782746  -51.007285   94.446552  48.251765  127.390459   54.292308
2012   -11.381881   -2.242177   89.940645  46.508065  116.029058   64.873077
2013    -8.157837   39.128467   89.924103  36.702593  117.600696   59.905556
2014   -30.808621    2.216089   83.024103  39.547222  119.545281   54.550000
2015     0.541412  117.575683   93.241875  40.312439  119.892258   64.273333
2016   -18.097567   40.183180   94.457500  42.494138  115.666916   75.754000
2017   -18.364158  -45.732075  102.910385  38.808788  118.535323  104.207500
2018   -14.846469  -55.401575  103.637083  45.206923  113.327250   59.770000
2019   -19.189139  151.007300   83.267778  39.022143  106.771591  120.820000

           hc_y_ft
events      double    home_run      single      triple
year
2009    241.547771  315.062600  168.031348  304.371229
2010    205.620004  321.388550  154.340679  251.386289
2011    256.424534  364.058388  179.665231  349.983923
2012    266.923297  368.121210  206.137295  325.330731
2013    266.961841  390.967959  202.475379  336.905056
2014    283.038841  384.339972  197.944496  349.383500
2015    259.231431  382.557017  197.136039  326.728133
2016    256.399025  377.473659  206.981086  299.978180
2017    236.703804  386.060524  200.297698  233.681525
2018    235.010596  371.152869  212.432508  337.220900
2019    282.471078  385.563407  227.707193  194.974400

In [8]:
df_avg.to_csv('plots.csv')

In [9]:
df_hits = df[(df['events']=='single') | (df['events']=='double') | (df['events']=='triple') | (df['events']=='home_run')]
df_hits["hc_x"] = pd.to_numeric(df_hits["hc_x"]).abs()
df_hits["hc_x_ft"] = pd.to_numeric(df_hits["hc_x_ft"]).abs()
df_hits["hc_y"] = pd.to_numeric(df_hits["hc_y"]).abs()
df_hits["hc_y_ft"] = pd.to_numeric(df_hits["hc_y_ft"]).abs()
df_avg_2 = pd.pivot_table(df_hits,index=['year'], columns = 'events', values = ["hc_y","hc_x","hc_y_ft","hc_x_ft"])
df_avg_2

/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/rmukherjee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

              hc_x                                         hc_x_ft  \
events      double    home_run      single      triple      double
year
2009    149.167143   36.140000  122.677500  136.977143  101.431557
2010    132.888929   90.561000  119.438333  127.396667  137.688854
2011    100.608621   65.792353  120.943028  104.108462  130.074259
2012    107.267419   95.964194  121.115072  125.037692  135.566165
2013    112.500513  109.102222  122.498783  142.793333  129.293492
2014     91.931538   99.732778  112.777416  126.951111  126.651033
2015    100.944063  114.649512  126.232366  176.461667  128.229366
2016    133.486250   99.358621  118.232804  143.246000  130.727563
2017     99.146923   85.939697  118.118387  106.372500  149.213200
2018     91.730833   82.183333  119.628125  102.222500  149.003500
2019    100.489444   76.539286  117.764318  190.810000  147.723294

                                                 hc_y                         \
events    home_run     single      triple      double   home_run      single
year
2009    209.373800  64.526438   38.598114  100.831429  69.280000  132.383542
2010    163.521730  61.284363  121.002078  116.251071  66.565000  138.259365
2011    165.743865  68.600972   93.481392   94.446552  48.251765  127.390459
2012    139.264100  60.651588  123.355577   89.940645  46.508065  116.029058
2013    105.832052  63.598059  102.804778   89.924103  36.702593  117.600696
2014    110.920944  67.743572   91.625956   83.024103  39.547222  119.545281
2015    115.824300  71.619440  117.575683   93.241875  40.312439  119.892258
2016    129.462834  75.535769   97.165660   94.457500  42.494138  115.666916
2017    132.113118  69.167929  157.770125  102.910385  38.808788  118.535323
2018    159.475356  67.953576  135.739975  103.637083  45.206923  113.327250
2019    149.048436  77.036684  151.007300   83.267778  39.022143  106.771591

                       hc_y_ft
events      triple      double    home_run      single      triple
year
2009     73.868571  241.547771  315.062600  168.031348  304.371229
2010     96.608889  207.177775  321.388550  155.912135  251.386289
2011     54.292308  256.424534  364.058388  179.665231  349.983923
2012     64.873077  266.923297  368.121210  206.137295  325.330731
2013     59.905556  266.961841  390.967959  202.475379  336.905056
2014     54.550000  283.038841  384.339972  197.944496  349.383500
2015     64.273333  259.231431  382.557017  197.136039  326.728133
2016     75.754000  256.399025  377.473659  206.981086  299.978180
2017    104.207500  236.703804  386.060524  200.297698  233.681525
2018     59.770000  235.010596  371.152869  212.432508  337.220900
2019    120.820000  282.471078  385.563407  227.707193  194.974400

In [10]:
df_avg_2.to_csv('plots2.csv')